[[plugins]] # Plugin Manager
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
let g:onedark_color_overrides={
\ "comment_grey": { "gui": "#696969", "cterm": "41", "cterm16": "6" },
\ "special_grey": { "gui": "#696969", "cterm": "41", "cterm16": "6" },
\}
colorscheme onedark
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'vimlab/split-term.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
nmap <Leader>f <Plug>(easymotion-overwin-f)
" s{char}{char} to move to {char}{char}
nmap s <Plug>(easymotion-overwin-f2)
" Move to line
nmap <Leader>l <Plug>(easymotion-overwin-line)
" Move to word
nmap <Leader>w <Plug>(easymotion-overwin-w)Plug>(easymotion-overwin-w)
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo= 'lambdalisue/nerdfont.vim'

[[plugins]] 
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
augroup END
'''

[[plugins]] 
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]] 
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
hook_add = '''
function! s:fern_settings() abort
nmap <silent> <buffer> p     <Plug>(fern-action-preview:toggle)
nmap <silent> <buffer> <C-p> <Plug>(fern-action-preview:auto:toggle)
nmap <silent> <buffer> <C-d> <Plug>(fern-action-preview:scroll:down:half)
nmap <silent> <buffer> <C-u> <Plug>(fern-action-preview:scroll:up:half)
endfunction

augroup fern-settings
autocmd!
autocmd FileType fern call s:fern_settings()
augroup END
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_theme = 'deus'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#branch#enabled = 1
let g:airline_powerline_fonts = 1 
let g:airline#extensions#whitespace#enabled = 0
let g:airline_section_c = '%t %M'
let g:airline_section_z = get(g:, 'airline_linecolumn_prefix', '').'%3l:%-2v'
" 変更がなければdiffの行数を表示しない
let g:airline#extensions#hunks#non_zero_only = 1 
let g:airline#extensions#default#layout = [
    \ [ 'a', 'b', 'c'],
    \ [ 'y', 'z' ],
    \] 
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\'_' : {
\ 'runner' : 'vimproc',
\ 'runner/vimproc/updatetime' : 30,
\ 'outputter/error/success': 'buffer',
\ 'outputter/error/error': 'quickfix',
\ 'outputter/buffer/opener': '20new',
\ 'outputter/buffer/close_on_empty': 1,
\ },
\}
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'machakann/vim-sandwich'
